:scrollbar:
:data-uri:
:toc2:
:USER_GUID: %GUID%
:USERNAME: %user%
:CLUSTER: %cluster%

== Overview

*OpenShift Container Platform* is a platform for developing and running containerized applications. It is designed to allow applications and the data centers that support them to expand from just a few machines and applications to thousands of machines that serve millions of clients.

In *OpenShift Container Platform 4.3*, you must use *RHCOS* for all control plane machines, but you can use *Red Hat Enterprise Linux* (*RHEL*) as the operating system for compute, or worker, machines. If you choose to use *RHEL* workers, you must perform more system maintenance than if you use RHCOS for all of the cluster machines.

With *OpenShift Container Platform 4.3*, if you have an account with the right permissions, you can deploy a production cluster in supported clouds by running a single command and providing a few values. You can also customize your cloud installation or install your cluster in your data center if you use a supported platform.

For clusters that use *RHCOS* for all machines, updating, or upgrading, *OpenShift Container Platform* is a simple, highly-automated process. Because *OpenShift Container Platform* completely controls the systems and services that run on each machine, including the operating system itself, from a central control plane, upgrades are designed to become automatic events.

=== Architecture

==== Servers

[cols="1,2",caption="",options="header"]
|===============
| Server Name  | Description
| workstation | Jump host for the Lab
| undercloud| Red Hat Openstack Director
| ctrl01 | Controller
| compute01 | Compute node (12 CPUs + 32 GB RAM)
| compute02 | Compute node (12 CPUs + 32 GB RAM)
|===============

==== Networks

[cols="1,3",caption="",options="header"]
|===============
| Network | Description
| 192.0.2.0/24 | OSP Control Plane + Floating IP (flat network)
| 10.128.0.0/14 | OCP Cluster Network
| 10.0.0.0/16 | OCP Machine network
| 172.30.0.0/16 | OCP Service Network
|===============


==== Floating Ips

[cols="1,3",caption="",options="header"]
|===============
| FIP | Description
| 192.0.2.XX | Autogenerated for the bootstrap
| 192.0.2.70 | Used for the API: api.summit.example.com
| 192.0.2.71 | Used for the APPS: *.apps.summit.example.com
|===============


