---
apiVersion: template.openshift.io/v1
kind: Template
message: |
  Created ${NAME} Deployment, Service, and Route

metadata:
  annotations:
    openshift.io/display-name: Bookbag
    tags: gpte
    template.openshift.io/bindable: "false"
  name: bookbag

parameters:
  - name: URL 
    required: true
  - name: NAME
    required: true
    value: bookbag
  - name: IMAGE
    required: true
  - name: OSPVNCIMAGE
    required: true
  - name: IMAGE_PULL_POLICY
    required: true
    value: IfNotPresent
  - name: OPENSHIFT_CONSOLE_IMAGE
    required: true
    value: quay.io/openshift/origin-console:4.2
  - name: WORKSHOP_VARS
    required: true
    value: '{}'
  - name: AUTH_USERNAME
    required: true
    value: '*'
  - name: AUTH_PASSWORD
    value: ''

objects:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}

  - apiVersion: v1
    kind: RoleBinding
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}
    roleRef:
      name: admin
    subjects:
    - kind: ServiceAccount
      name: ${NAME}

  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: ${NAME}
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app: ${NAME}
            name: ${NAME}
        spec:
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          serviceAccountName: ${NAME}
          volumes:
            - name: envvars
              configMap:
                defaultMode: 0644
                name: ${NAME}-env
            - name: workshopvars
              configMap:
                defaultMode: 0644
                name: ${NAME}-vars
            - name: shared
              emptyDir: {}
          initContainers:
            - name: setup-console
              command:
                - /opt/workshop/bin/setup-console.sh
              env:
                - name: CLUSTER_SUBDOMAIN
                - name: OPENSHIFT_PROJECT
                - name: OPENSHIFT_USERNAME
                - name: OPENSHIFT_PASSWORD
                - name: OPENSHIFT_TOKEN
                - name: OC_VERSION
                - name: ODO_VERSION
                - name: KUBECTL_VERSION
              image: ${IMAGE}
              imagePullPolicy: IfNotPresent
              resources: {}
              volumeMounts:
                - mountPath: /var/run/workshop
                  name: shared
          containers:
            - resources:
                limits:
                  memory: 512Mi
              readinessProbe:
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 3
                timeoutSeconds: 3
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              terminationMessagePath: /dev/termination-log
              name: osp-vnc
              livenessProbe:
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 30
                timeoutSeconds: 3
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              env:
                - name: APP_CONFIG
                - name: DJANGO_SECRET_KEY
                  value: "1234"
              ports:
                - containerPort: 8080
                  protocol: TCP
              imagePullPolicy: IfNotPresent
              terminationMessagePolicy: File
              image: ${OSPVNCIMAGE}
              imagePullPolicy: ${IMAGE_PULL_POLICY}
    
            - name: terminal
              env:
                - name: APPLICATION_NAME
                  value: ${NAME}
                - name: AUTH_USERNAME
                  value: ${AUTH_USERNAME}
                - name: AUTH_PASSWORD
                  value: ${AUTH_PASSWORD}
                - name: CLUSTER_SUBDOMAIN
                - name: OAUTH_SERVICE_ACCOUNT
                  value: ${NAME}
                - name: DOWNLOAD_URL
                - name: WORKSHOP_FILE
                - name: CONSOLE_URL
                  value: ""
                - name: OC_VERSION
                - name: ODO_VERSION
                - name: KUBECTL_VERSION
                - name: WORKSHOP_VARS
                  value: ${WORKSHOP_VARS}
              image: ${IMAGE}
              imagePullPolicy: ${IMAGE_PULL_POLICY}
              ports:
                - containerPort: 10080
                  protocol: TCP
              resources: {}
              volumeMounts:
                - mountPath: /opt/workshop/envvars
                  name: envvars
                - mountPath: /var/run/workshop
                  name: shared
            - name: console
              command:
                - /var/run/workshop/start-console.sh
              env:
                - name: BRIDGE_K8S_MODE
                  value: in-cluster
                - name: BRIDGE_LISTEN
                  value: http://0.0.0.0:10083
                - name: BRIDGE_BASE_PATH
                  value: /console/
                - name: BRIDGE_PUBLIC_DIR
                  value: /opt/bridge/static
                - name: BRIDGE_USER_AUTH
                  value: disabled
                - name: BRIDGE_BRANDING
                  value: openshift
              image: ${OPENSHIFT_CONSOLE_IMAGE}
              imagePullPolicy: IfNotPresent
              resources: {}
              volumeMounts:
                - mountPath: /var/run/workshop
                  name: shared

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}
    spec:
      ports:
      - name: 10080-tcp
        port: 10080
        protocol: TCP
        targetPort: 10080
      selector:
        name: ${NAME}
      type: ClusterIP

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${NAME}
      name: ospvnc${NAME}
    spec:
      ports:
      - name: 8080-tcp
        port: 8080 
        protocol: TCP
        targetPort: 8080 
      selector:
        name: ${NAME}
      type: ClusterIP



  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}
    spec:
      port:
        targetPort: 10080-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      host: "${URL}"
      to:
        kind: Service
        name: ${NAME}

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: ${NAME}
      name: redovn${NAME}
    spec:
      port:
        targetPort: 8080-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      host: "${URL}"
      path: "/console"
      to:
        kind: Service
        name: ospvnc${NAME}



  - apiVersion: v1
    data:
      gateway.sh: ""
      terminal.sh: ""
      workshop.sh: ""
    kind: ConfigMap
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}-env

  - apiVersion: v1
    data: {}
    kind: ConfigMap
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}-vars
